name: RunicMod
version: '${version}'
main: com.runicrealms.plugin.runicmod.RunicMod
api-version: '1.19'
author: 'BoBoBalloon'
depend:
  - RunicCommon
  - RunicItems
  - RunicCore
  - RunicChat
  - RunicDatabase
  - RunicBank
  - RunicPvP
  - RunicNpcs
